name: Update EasyDutch AdGuard

on:
  schedule:
    - cron: "00 10 * * 6"
  workflow_dispatch:

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Update EasyDutch AdGuard
    runs-on: ubuntu-latest
    steps:
      - name: Clone EasyDutchCDN
        uses: actions/checkout@v3
      - name: Copy EasyDutch filters to EasyDutch AdGuard
        run: |
          TMPDIR=$(mktemp -d)
          git clone --depth=1 --single-branch --branch=gh-pages https://github.com/EasyDutch-uBO/EasyDutch.git $TMPDIR
          cp $TMPDIR/EasyDutch/*.txt EasyDutch/
      - name: Commit changes (if any)
        run: |
          if [[ -n $(git diff) ]]; then
            git config user.name "BPower0036"
            git config user.email "<>"
            git add -u EasyDutch/
            git commit -m "Updated from @EasyDutch-uBO/EasyDutch"
            git push origin main
          fi
